### ISSUE TITLE
Migrating over community-driven project 

### ISSUE THREAD

**Issue by Zerrossetto** [dbader/schedule#105]
To everyone interested,
in this last weeks I tried to contact the author of the library in order to let the project move on again.
This was due to the fact that the author itself hasn't accepted a single PR or committed a line from the 6th of march of this year, and the code itself began to age (no CI tools integration with 3.4/3.5, to cite one). Anyhow the contact attempt failed, and I never got a feedback.
What I thought now, after a [brief discussion](https://github.com/dbader/schedule/pull/102) with @laubed was that maybe the project could continue in another repository, possibly keeping the fork with the original project and possibly having more than one contributor in order to ensure that any author defections will never let the project lag behind.

I'm surely still hoping that the author will return, and if he will we also pull the forked version over his. 
Please, tell me if you see any other solution than this, otherwise we'll organize a place for discussing more deeply the topic.

**Comment by dbader** [comment]
Hi @Zerrossetto,

I can tell from reading this that you and @laubed care a lot about schedule. And that's awesome!

Like you pointed out I haven't had much time to spend on schedule since spring. I can see why you're upset about the lack of feedback from me on issues and pull-requests.

On the other hand I'm a bit surprised by the sense of "mutiny" I'm getting from issue and the email I got from @laubed last night 😉 But I dig the passion you guys have for the project, so it's all good with me. Well, and that tactic did finally get a response from me, right? 😀

Anyway, I'll admit I've been hesitant to add more folks with write access to the repo. 

Mainly because the proposals I've gotten so far didn't seem to want to take the project into a direction that I felt was sensible – or they didn't propose any direction at all and just asked for write access.

(I'm getting about one "gimme commit access OR ELSE!!111" email a month for this project and that gets old fast. I don't really want to hand out commit rights to folks with the social graces of a sea cucumber.)

One thing I want to avoid is growing schedule "randomly" by adding half-baked or too niche features. I think people like schedule because it's interface is simple and straight-forward. I'm worried it will lose its simplicity. I don't think we should build another APScheduler or a replacement for Cron.

But, I also realize I didn't really take the time to explain myself well or start some kind of discussion for a road map. 

Sorry about that!

I want to fix this now. Here's what I'm going to do:

* I'll triage open issues and PRs so we can move these along or close where necessary
* I'll start some kind of roadmap discussion issue so we can hash out next steps
* Work on the next PyPI release for schedule

Of course, you're still free to start a fork according to the license. But I'd much rather continue working on this with you together in this repo. It will be easier for users and from a visibility perspective. And like you said it will be difficult to get traction with a fork.

Looking forward to hear your and @laubed's thoughts and input on the soon to come roadmap ticket 😃 

Take care,
– Dan

**Comment by laubed** [comment]
Good to hear from you!
I really did not want to offend you. Maybe that mail sounded a bit harsh but it was not meant to be that way. 
Looking forward for a roadmap to further improve this library in a structured way.

**Comment by Zerrossetto** [comment]
Actually no mutiny, and probably the tone you read is just from the fact that I'm writing out of my mother tongue, so excuse me if it sounded harsh. Anyway if we actually wanted to steal your work I wouldn't certainly write this inside your own project issue list. For me the only concern was that this project wasn't proceeding to much, also while running it I noticed the time drifting issue that's also been described by one of the pull requests.

I sincerely hope we'll be able to work together on this.

Bye.

**Comment by dbader** [comment]
Alright, sweet 😃  Let's see if we can do something cool with Schedule in the future! I'll be digging into current issues and PRs shortly.
