### ISSUE TITLE
ret = job.run() ?  what is the connection between ret and CancelJob?

### ISSUE THREAD

**Issue by yasinasama** [dbader/schedule#153]
Hi!  I just can not understand this method.
def _run_job(self, job):
        ret = job.run()
        if isinstance(ret, CancelJob) or ret is CancelJob:
            self.cancel_job(job)

I think the ret and CancelJob is not related.ret just the return by my function.
How to cancel job with your method.

**Comment by trp07** [comment]
I am wondering the same thing.  I've tried playing around with the code, but I can't seem to get that method to work.  The only way I know how to cancel a job, at the moment, is by the following code snippet:

``
>>> def func1():
           print('hello')

>>> def func2():
          print('goodbye')

# add both jobs
>>> a = schedule.every(5).seconds.do(func1)
>>> b = schedule.every(10).seconds.do(func2)

# print out list of jobs
>>> schedule.default_scheduler.jobs
[Every 5 seconds do func1() (last run: [never], next run: 2017-08-07 22:28:50), Every 10 seconds do func2() (last run: [never], next run: 2017-08-07 22:29:18)]


>>> schedule.cancel_job(a)

# print out jobs list again.  note the first job is missing since it was cancelled.
>>> schedule.default_scheduler.jobs
[Every 10 seconds do func2() (last run: [never], next run: 2017-08-07 22:31:03)]
``

**Comment by dbader** [comment]
Hey there, please check out the FAQ items related to job cancellation: https://schedule.readthedocs.io/en/stable/faq.html#how-can-i-run-a-job-only-once

Does this help?

**Comment by yasinasama** [comment]
Thanks @dbader and @trp07 !
[https://schedule.readthedocs.io/en/stable/faq.html#how-can-i-run-a-job-only-once](url)
It is useful!
