### ISSUE TITLE
Will you accept a PR that lets users schedule to the second?

### ISSUE THREAD

**Issue by NathanWailes** [dbader/schedule#266]
### Background
I'm working for a company that is trying to develop software to manage the electronic TV-screen-sized ad-billboards you see in malls.  The billboard software needs to be able to schedule various events throughout the day, with the events often needing to be scheduled to the second or possibly even tenth or hundredth of a second.  The CTO recommended using this `schedule` package to handle this.

### The problem
I've noticed that the `at()` function in this package does not allow users to schedule things to the second or millisecond, and I'm wondering if I can submit a PR that will add this functionality, or if there's some other package that I should consider instead.  For example, I've spent a few minutes looking at the Python built-in `sched` package and it seems like it may do what I need.  It seems like this `schedule` package is really meant more for cron-job-like tasks.

**Comment by dbader** [comment]
Hey @NathanWailes I don't really see a use case for millisecond precision because `schedule` wasn't built with that in mind. Like you said this is meant to be a `cron` replacement and not a real-time scheduler.

However I'd be interested in making `at()` accept timestamps with 1 second precision, e.g. `at("13:00:30")`. If you're interested in putting together a PR for that let me know! Oh, and Happy New Year 🎆 :-)

**Comment by NathanWailes** [comment]
Thanks for the quick response!  I asked the CTO and he said he'd be OK with 1 second precision, so I created a PR: https://github.com/dbader/schedule/pull/267

Happy New Year!
