### ISSUE TITLE
scheduler does not account for job execution time

### ISSUE THREAD

**Issue by bitworm** [dbader/schedule#268]
It seems that schedule does not account for the time it takes the scheduled job to complete.  For example:

```
import schedule
from datetime import datetime
from time import sleep

def job(seconds):
    print(datetime.now().strftime('%H:%M:%S.%f'))
    sleep(seconds)

schedule.every(10).seconds.do(job, 2)
while True:
    schedule.run_pending()
```

This code example executes `job` every 12 seconds instead of every 10.  This is not noticeable if jobs are short - but in my case they may take several hours (delay is 1 day), so this is quite problematic.

**Comment by MikeDoes** [comment]
This issue has been resolved before:
https://schedule.readthedocs.io/en/stable/faq.html#how-to-execute-jobs-in-parallel

Explanation:
Kindly use the threading library as the docs recommend.

I had the same problem. I told the function to launch every 6 hours so I got a split like so: 6:26, 12:27, 18:28, 0:29,6:30.
This is because it executes the software serially, where as you wish do execute it in parallel. I came from a JS background where functions execute asynchronously, where this issue wouldn't have arised. But of course, the giant upside is the versatility of python.

**Comment by dbader** [comment]
Added an FAQ item, thanks @MikeDoes!

**Comment by bitworm** [comment]
The code I have written does not require parallel execution - the job takes 2 sec and the delay is 10 seconds.  One wouldn't think to look at the parallelization section of the documentation to achieve serially scheduled tasks.

The main problem is the syntax implies a scheduling service (`schedule.every(10).seconds.do(job, 2)`), but the actual behavior is more like `timeout(10).seconds.between.start(job, 2)` or something.  This is a source of confusion for anyone wanting scheduled jobs.   My recommendation is to make the code behavior reflect the actual code syntax.

**Comment by bitworm** [comment]
It looks like several users have unwittingly run into this issue, and may not know the cause:
- https://github.com/dbader/schedule/issues/207
- https://github.com/dbader/schedule/issues/174
- https://github.com/dbader/schedule/issues/163
- https://github.com/dbader/schedule/issues/144
