### ISSUE TITLE
get next_run from within job

### ISSUE THREAD

**Issue by d33tah** [dbader/schedule#309]
Consider the example:

```python
#!/usr/bin/env python3

import time
import logging

import schedule

LOGGER = logging.getLogger()


def perform_job(notify_user_id):
    time.sleep(10.0)
    LOGGER.info('Job done. Will sleep now until %s.', schedule.next_run())


def main():
    schedule.every().day.at("10:00").do(perform_job)
    schedule.every().day.at("18:00").do(perform_job)
    LOGGER.info('Scheduler started. Will now sleep until %s.',
                schedule.next_run())
    while True:
        schedule.run_pending()
        time.sleep(1)


if __name__ == '__main__':
    main()
```

The problem is, `Job done. Will sleep now until %s` will tell me about the "next job" that's actually the current one because `perform_job` hadn't finished yet. If `run_pending` returned a boolean saying whether anything was executed I could use it to solve the problem, but that's not the case. Are there any other solutions?

**Comment by SijmenHuizenga** [comment]
Hi @d33tah, thanks for raising this question. Unfortunately it is not possible to retrieve the next_run of a job from within the job itself. This is because the timestamp at which the job finishes is used to calculate the next run of the job. That's why the next_run is calculated _after_ the job finishes. Since we don't know when the job finishes while the job is in progress there is no way to calculate when the next run takes place.
