### ISSUE TITLE
Schedule persistence and Listing all active/pending jobs

### ISSUE THREAD

**Issue by dojo-technology** [dbader/schedule#377]
Not sure if this is the right channel but I have a question.

Once I define job schedules, is there a way to list them? for example, list all active/pending jobs?
Another question is, how persistent is the job schedule? In case I restart application, it will get lost the schedule created?

**Comment by stravi** [comment]
@dojo-technology I was right now looking for the same. I love the interface of the schedule comparing to system crontab, but it seems there is no save/serialize to a file in order to persist the schedule between each run. 
Maybe someone can extend it at store jobs in a file as a dict..

**Comment by dojo-technology** [comment]
@stravi and by the way, crontab persists the schedule?

**Comment by stravi** [comment]
> @stravi and by the way, crontab persists the schedule?

Yeap, it's based on linux cron jobs which are based on writing jobs to a file :D. For my project I ended up using [apscheduler](https://apscheduler.readthedocs.io/en/stable/userguide.html) and I am saving jobs using [sqlalchemystore](https://apscheduler.readthedocs.io/en/stable/modules/jobstores/sqlalchemy.html#apscheduler.jobstores.sqlalchemy.SQLAlchemyJobStore)

**Comment by SijmenHuizenga** [comment]
Schedule does not support job persistence because we want to keep this library super simple. If you do need to store jobs between restarts it is better to switch to some more advanced scheduling library like apscheduler.

To retrieve the list of scheduled jobs, use `schedule.jobs`. It returns a list of Job objects. An example:

```python
import schedule

def job():
    pass

schedule.every(5).to(10).minutes.do(job)
print(schedule.jobs)

schedule.clear()
print(schedule.jobs)

schedule.every(20).seconds.do(job)
print(schedule.jobs)
```
outputs:
```
[Every 5 to 10 minutes do job() (last run: [never], next run: 2020-11-21 13:59:14)]
[]
[Every 20 seconds do job() (last run: [never], next run: 2020-11-21 13:50:34)]

```

**Comment by dberardo-com** [comment]
this works for me ... do you see any downsides ?


```py

import dill

def persist_scheduler(scheduler, filename="scheduler.pickle"):
    logger.info("Saving scheduler into {}/{}".format(os.path.dirname(SCHEDULE_PATH), filename))
    with open("{}/{}".format(os.path.dirname(SCHEDULE_PATH), filename), "wb") as f:
        dill.dump(scheduler.jobs, f)


def load_persisted_scheduler(filename="scheduler.pickle"):
    logger.info("Loading scheduler from {}/{}".format(os.path.dirname(SCHEDULE_PATH), filename))
    with open("{}/{}".format(os.path.dirname(SCHEDULE_PATH), filename), "rb") as f:
        s = schedule.Scheduler()
        s.jobs = dill.load(f)
        return s

```

i only see the downside that functions are also serialized, so if one changes the actions ("do(...)") definitions, those will not be reflected in the deserialized version of the scheduler.

**Comment by dberardo-com** [comment]
btw, if persistency were to be implemented with the approach above, a whole lot of new features could be supported by this library, such as:

* job.run_once() --> guarantees that the job will run only once
* job.catchup --> the job will be run N times in order to catchup for missed schedules

and so on.

hope the maintainers will opt for this (optional) behavior. the extra dill dependency would be managed at install time with: pip install schedule[persistency]
