### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by mjvithesh** [dbader/schedule#389]
i have installed using 'pip install schedule'
when i try to import in a python file, the error shows 'no module named schedule'

**Comment by 07pepa** [comment]
this is likely problem on your side ... and you provided little details

i would try python clean install or diferent computer

**Comment by SijmenHuizenga** [comment]
Hi there! `no module named schedule` can be quite annoying. Unfortunately it is something that has to be solved on your computer, as the error indicates that the package was not installed correctly. Here are some pointers to get you started:

Validate that you installed schedule in python 3 using "`pip3 list | grep schedule`.

Are you using the same Python version to install Schedule and execute your code? For example, if you installed schedule using a version of pip that uses Python 2, and your code runs in Python 3, the package won't be found. In this case the solution is to install Schedule using pip3: ``pip3 install schedule``.

Are you using virtualenv? Check that you are running the script inside the same virtualenv where you installed schedule.

Is this problem occurring when running the program from inside and IDE like PyCharm or VSCode? Try to run your program from a commandline outside of the IDE. If it works there, the problem is in your IDE configuration. It might be that your IDE uses a different Python interpreter installation.

Hope this gets you a step closer to a solution.
