### ISSUE TITLE
Shouldn't it support one queue per job

### ISSUE THREAD

**Issue by thunderock** [dbader/schedule#393]
Attaching script to reproduce this issue. I'm trying to run two separate jobs per second, but second job runs after 10 seconds.

`
import datetime
import schedule
import time

#this scheduler has one queue
#need to add separate queue for every job

def format_time(t):
&nbsp;&nbsp;&nbsp;&nbsp;return t.strftime('%Y-%m-%d %H:%M:%S') if t else '[never]'

def job1(message='non'):
&nbsp;&nbsp;&nbsp;&nbsp;print("I'm second job running: {0} at {1}".format(message, format_time(datetime.datetime.now())))
   &nbsp;&nbsp;&nbsp;&nbsp;time.sleep(10)

def job(message='stuff'):
   &nbsp;&nbsp;&nbsp;&nbsp;print("I'm working on : {0} at {1} ".format(message, format_time(datetime.datetime.now())))
   &nbsp;&nbsp;&nbsp;&nbsp;time.sleep(10)

schedule.every().second.do(job1)
schedule.every().second.do(job)

while True:
    &nbsp;&nbsp;&nbsp;&nbsp;schedule.run_pending()
`

**Comment by SijmenHuizenga** [comment]
Hi there! `schedule.run_pending` runs all jobs that were scheduled to run since the last `schedule.run_pending` call sequentially. In this case, job1 takes 10 seconds to execute. Only after that is finished, job gets launched. If you want to run jobs in parallel, take a look at [this example](https://schedule.readthedocs.io/en/stable/faq.html#how-to-execute-jobs-in-parallel).

**Comment by thunderock** [comment]
Sure thing. makes sense. for some reason thought that should be the responsibility of this codebase itself.

**Comment by thunderock** [comment]
Please close this issue if you want to.
