### ISSUE TITLE
Telegram Bot Updater + schedule

### ISSUE THREAD

**Issue by buinguyenhoangtho** [dbader/schedule#443]
![image](https://user-images.githubusercontent.com/76900905/110051831-1e766800-7d89-11eb-84a3-dffc94cc327e.png)

hi. i'm currently using your library for schedule my Telegram bot who send message into my channel. I'm trying to combine with it but no luck of it. Can you help me what happened with my script? Tried with there own daily code but so hard to use  it

**Comment by SijmenHuizenga** [comment]
It seems `main()` is in the wrong place. I guess you don't want to schedule a new 2-second job every second? 

Also keep in mind that `run_pending` needs to be called every second. If `Updater()` is blocking, `run_pending` is never reached. See [this documentation](https://schedule.readthedocs.io/en/stable/background-execution.html) for an example on how to run schedule in the background. 

PS: Next time, please copy-paste the code instead of a screenshot, that makes it easier to read ;)

**Comment by buinguyenhoangtho** [comment]
Apologize. I forgot to said that i'm solved it. Thanks for your help :D
