### ISSUE TITLE
How do you start the job automatically without having to type "example_file.py" command

### ISSUE THREAD

**Issue by corkin** [dbader/schedule#458]
First time trying to implement something like this. 

When I run "python example_file.py" the jobs run at the given intervals. I'm trying to figure out how I now can run this automatically without having to use the command "python example_file.py" 

Currently trying to implement this with Heroku.

Any help is appreciated. Thanks!

**Comment by DoomCreature** [comment]
I do have almost the same question.
While using background task I do not know how to start the task properly.

Even commenting the _stop_run_continuously.set()_ the jobs never begins.
And when I did call the _def anyname():_ I created for each job or the _run_continuously_ all the jobs runs twice.

I do hope they answer your question @corkin because will for sure help me as well .
And unfortunately I didn't find anything in stack or google...

**Comment by SijmenHuizenga** [comment]
Hi! This library is an _in process_ scheduling library, meaning that it only runs inside a python script. There is way to schedule jobs using this library without running a python process.

However, you could look into automatically running `python example_file.py` whenever Heroku starts your app.

**Comment by corkin** [comment]
Thanks for the reply. Yes, I just ended up using the Heroku Scheduler add on to automatically run the script.
