### ISSUE TITLE
Is schedule thread or process (multiprocessing) safe?   No jobs when schedule.get_jobs() called from thread?

### ISSUE THREAD

**Issue by dachshund-digital** [dbader/schedule#478]
Is schedule thread or process (multiprocessing) safe?   No jobs when schedule.get_jobs() called from thread?

I import schedule, create a job, then query get_jobs() shows 1 job.  All good.  I then query get_jobs() within a multiprocessing thread, and it shows 0 jobs.  So I am tripping over a scope or namespace issue?  Or is something else happening here?

**Comment by rocky4546** [comment]
I have schedule running in a multiprocessing system where some jobs are inline, some are threaded and some launch separate processes.  It all works.  What you are asking is different... whether the data/variables in one thread (schedule objects are in this thread) can somehow be present in another thread or process.  The answer is in general no. Also, if you are running in Windows, it gets even harder with python because processes are not forked.  This means a copy of the objects are not present in sub-processes unless you are using pickling.  Python recommends providing the object to another thread through a multi-processing queue.

**Comment by dachshund-digital** [comment]
I am on Linux, and no, there is no inter-process communication needed per se.  Just seems that run_pending() does not have a reference to the default schedule object as expected.  What I may, likely, have to do... is create a scheduler as a multiprocessing object variable and pass that to the multiprocessing process that needs said object.  This would ensure that the given schedule instance is 'seen' by the main process as well as the child process.  I guess I was expecting the default scheduler to be seen across namespaces... which in python is not really the norm.
