### ISSUE TITLE
ImportError: cannot import name 'Scheduler' from 'schedule'

### ISSUE THREAD

**Issue by julesnicolsontabuno** [dbader/schedule#545]
Cannot migrate and run my Django project because of this error. I am using Python 3.8.7

**Comment by jross-7437** [comment]
I have the same problem, I'm running Python3.10 on MacOS,  "from schedule import every" fails with words about circular referencing problems. Ditto "from schedule import Scheduler"   - "from schedule import *" doesn't work either

**Comment by SijmenHuizenga** [comment]
This could happen when your code imports the wrong ``schedule`` module. Maybe there is a file `schedule.py` in your project that overrides the ``schedule`` module provided by this library?

Since this issue was created ~half a year ago i assume it has been resolved. If not, feel free to create a new one.
