### ISSUE TITLE
How distributed can schedule become?

### ISSUE THREAD

**Issue by lifeisstillgood** [dbader/schedule#59]
I came across this project on HN and am putting together my mental team of projects for a software literate company - and wanted to understand a bit more.

Cron suffers from being fixed to one machine - whereas a company or organisation almost be default has more than one server and wants to load balance in some form

The first part (distributed job definitions) seems simple - text files can be as distributed as you like and brought together

The next stage is after the jobs have been scheduled, to have them sent out and run on more than one server - to have a grid, treat it as a grid and scheduler for it 

How amenable is the schedule package to that step (or is it already there and I can stop worrying!)

**Comment by douglascamata** [comment]
@lifeisstillgood I suggest you take a look at [http://www.celeryproject.org/](Celery) as this is a much simpler egg and I think this has a very difference objective.

**Comment by dbader** [comment]
Thanks for reaching out! I agree that you'd probably want to look into Celery and use schedule in a pattern like the one described here: http://adam.herokuapp.com/past/2010/4/13/rethinking_cron/

**Comment by thnee** [comment]
Absolutely agree that for any kind of serious production you need redundancy. But I don't think it has to be so complicated to involve sending job executions over the network. (Rather, if there is a heavy workload in some job, then the job itself can decide to offload it to a queue task via Celery or any other system).

I don't think it would take much. If this library would improve separation of concerns, users could plugin whatever they need by overriding methods in the scheduler.

For example, `_schedule_next_run` contains some of the most useful logic for calculating stuff, but also reads and writes directly to `self.next_run`. If there were `set_next_run` and `get_next_run` methods, I could easily override them and save the value to a database using atomic transactions. Then it would be no problem to run the scheduler on multiple machines at the same time. (I might of course be missing some other points, but hopefully you get the idea). Thoughts, anyone?

Of course a locking mechanism is also a good idea. But that doesn't have to be part of this library.

As it stands, this library looks so nice, I would love to get access to the fancy semantics of declaring schedules, but am not really able to use it because of this issue.

Sorry if necro is not appreciated, but I searched and found this and it is exactly the issue that I would have opened myself.
